apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: parakeet-models
  namespace: poc-parakeet-cpp
  labels:
    app: parakeet-cpp
    autopoc.io/project: parakeet-cpp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
